name = "libneo"
version = "0.3.0"
license = "MIT"
author = "Christopher Albert"
maintainer = "albert@tugraz.at"
copyright = "Copyright 2025, Plasma Physics at TU Graz"

[dependencies]
fortio = { git = "https://github.com/lazy-fortran/fortio.git", rev = "38add03dc691a7cd4715cd3e611ad42422e46091" }
fortnum = { git = "https://github.com/lazy-fortran/fortnum.git", rev = "1a52e13c5e28b09d083947a6ec7e8a1dcf9d502e" }

[build]
external-modules = [
    "fftw3", "fftw3.f03",
    "omp_lib", "mpi", "mpi_f08",
    "openacc"
]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
link = ["pthread"]

[install]
library = true

[fortran]
implicit-typing = true
implicit-external = true
source-form = "free"
