name = "libneo"
version = "0.3.0"
license = "MIT"
author = "Christopher Albert"
maintainer = "albert@tugraz.at"
copyright = "Copyright 2025, Plasma Physics at TU Graz"

[dependencies]
fortio = { git = "https://github.com/lazy-fortran/fortio.git", rev = "27e7e17ecc6f272f44ae42a5718b9a4a3c449cfc" }
fortnum = { git = "https://github.com/lazy-fortran/fortnum.git", rev = "62a559c0b8e1b28bd63550164a09ed9644e659b1" }

[build]
external-modules = [
    "fftw3", "fftw3.f03",
    "omp_lib", "mpi", "mpi_f08",
    "openacc"
]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = true
implicit-external = true
source-form = "free"
