if(NOT DEFINED COMPILE_COMMANDS OR NOT EXISTS "${COMPILE_COMMANDS}")
  message(FATAL_ERROR "COMPILE_COMMANDS must name an existing compile_commands.json")
endif()

if(NOT DEFINED SOURCE_ROOT)
  message(FATAL_ERROR "SOURCE_ROOT must name the libneo source directory")
endif()

file(READ "${COMPILE_COMMANDS}" compile_database)
string(JSON command_count LENGTH "${compile_database}")
if(command_count EQUAL 0)
  message(FATAL_ERROR "Compile database is empty")
endif()

math(EXPR final_command_index "${command_count} - 1")
set(checked_command_count 0)
foreach(command_index RANGE 0 ${final_command_index})
  string(JSON source_file GET "${compile_database}" ${command_index} file)
  string(FIND "${source_file}" "${SOURCE_ROOT}/src/" source_prefix)
  if(NOT source_prefix EQUAL 0 OR NOT source_file MATCHES "\\.(f90|F90)$")
    continue()
  endif()

  string(JSON command GET "${compile_database}" ${command_index} command)
  if(command MATCHES "(^| )-ffast-math( |$)")
    message(FATAL_ERROR "Deterministic libneo command enables -ffast-math: ${source_file}")
  endif()
  if(command MATCHES "(^| )-ffp-contract=fast( |$)")
    message(FATAL_ERROR "Deterministic libneo command enables fast contraction: ${source_file}")
  endif()
  if(NOT command MATCHES "(^| )-fno-fast-math( |$)")
    message(FATAL_ERROR "Deterministic libneo command lacks -fno-fast-math: ${source_file}")
  endif()
  if(NOT command MATCHES "(^| )-ffp-contract=off( |$)")
    message(FATAL_ERROR "Deterministic libneo command lacks -ffp-contract=off: ${source_file}")
  endif()
  math(EXPR checked_command_count "${checked_command_count} + 1")
endforeach()

if(checked_command_count EQUAL 0)
  message(FATAL_ERROR "No libneo Fortran source compile commands were checked")
endif()
