"""Tests for eqdsk_to_boozer_chartmap: circular equilibrium verification.

Circular tokamak parameters (from circ.eqdsk generated by gen_circular_eqdsk.py):
  R0 = 1.60 m, a = 0.50 m, B0 = 2.0 T, fpol = R0*B0 = 3.2 T*m
  q(r) = Q0 + (QA - Q0) * (r/a)^2,  Q0=1.5, QA=4.0

The efit_to_boozer field-line integrator computes toroidal flux and q(s) on
the numerical psi grid of the EQDSK.  For this coarse 65x65 synthetic
equilibrium the toroidal flux from integration differs from the geometric
formula B0*pi*a^2 because the 1/R weighting is applied on the psi grid.
Tests verify self-consistency of the converter output and structural properties,
not perfect agreement with analytic large-aspect-ratio formulas.
"""

from pathlib import Path
import numpy as np
import pytest

TESTS_DIR = Path(__file__).parent
CIRC_EQDSK = TESTS_DIR / "circ.eqdsk"

R0 = 1.60   # m
A = 0.50    # m
B0 = 2.0    # T

METER_TO_CM = 1.0e2
TESLA_TO_GAUSS = 1.0e4


@pytest.fixture(scope="module")
def chartmap_path(tmp_path_factory):
    """Build the chartmap once per test module, cached to disk."""
    pytest.importorskip("netCDF4")
    if not CIRC_EQDSK.exists():
        pytest.skip(f"circular g-file not found: {CIRC_EQDSK}")

    try:
        import _efit_to_boozer  # noqa: F401
        from efit_to_boozer.boozer import get_magnetic_axis  # noqa: F401
    except ImportError:
        pytest.skip("_efit_to_boozer not available")

    import libneo
    src = str(Path(__file__).resolve().parents[1] / "libneo")
    if src not in libneo.__path__:
        libneo.__path__.insert(0, src)

    from libneo.eqdsk_to_boozer_chartmap import convert_eqdsk_to_chartmap

    out = tmp_path_factory.mktemp("chartmap") / "circ_boozer.nc"
    convert_eqdsk_to_chartmap(
        CIRC_EQDSK,
        out,
        nrho=20,
        ntheta=48,
        nstep=500,
        nlabel=50,
        ntheta_int=50,
        nsurfmax=20,
        nsurf=50,
    )
    return out


def _read_chartmap(path):
    """Return dict of chartmap arrays."""
    import netCDF4
    d = {}
    with netCDF4.Dataset(path) as ds:
        d["rho"] = np.asarray(ds.variables["rho"][:])
        d["s"] = np.asarray(ds.variables["s"][:])
        d["theta"] = np.asarray(ds.variables["theta"][:])
        d["zeta"] = np.asarray(ds.variables["zeta"][:])
        d["Bmod"] = np.transpose(np.asarray(ds.variables["Bmod"][:]), (2, 1, 0))
        d["x"] = np.transpose(np.asarray(ds.variables["x"][:]), (2, 1, 0))
        d["y"] = np.transpose(np.asarray(ds.variables["y"][:]), (2, 1, 0))
        d["z"] = np.transpose(np.asarray(ds.variables["z"][:]), (2, 1, 0))
        d["A_phi"] = np.asarray(ds.variables["A_phi"][:])
        d["B_theta"] = np.asarray(ds.variables["B_theta"][:])
        d["B_phi"] = np.asarray(ds.variables["B_phi"][:])
        d["torflux"] = float(ds.torflux)
        d["nfp"] = int(np.asarray(ds.variables["num_field_periods"][:]).item())
    return d


def test_axisymmetric_structure(chartmap_path):
    """Chartmap has nfp=1, nzeta=1: axisymmetric structure."""
    d = _read_chartmap(chartmap_path)
    assert d["nfp"] == 1, f"expected nfp=1, got {d['nfp']}"
    assert d["Bmod"].shape[2] == 1, (
        f"expected nzeta=1 for axisymmetric chartmap, got {d['Bmod'].shape[2]}"
    )


def test_magnetic_axis(chartmap_path):
    """Magnetic axis R ≈ R0 and Z ≈ 0 from the innermost surface geometry."""
    d = _read_chartmap(chartmap_path)
    R_cm = np.sqrt(d["x"][:, :, 0] ** 2 + d["y"][:, :, 0] ** 2)
    Z_cm = d["z"][:, :, 0]
    R_innermost = R_cm[0].mean()
    Z_innermost = Z_cm[0].mean()
    # Axis within a/2 = 25 cm of R0; innermost surface is at small but finite s
    assert abs(R_innermost / METER_TO_CM - R0) < 0.25, (
        f"R_innermost = {R_innermost/METER_TO_CM:.3f} m, expected ~{R0} m"
    )
    assert abs(Z_innermost) < 5.0, (
        f"|Z_innermost| = {abs(Z_innermost):.3f} cm, expected ~0"
    )


def test_bmod_1_over_R(chartmap_path):
    """Angle-averaged Bmod follows the 1/R tokamak falloff to within 7%."""
    d = _read_chartmap(chartmap_path)
    nrho = len(d["rho"])
    for k in range(nrho):
        R_cm = np.sqrt(d["x"][k, :, 0] ** 2 + d["y"][k, :, 0] ** 2)
        R_mean_m = R_cm.mean() / METER_TO_CM
        B_analytic_G = B0 * TESLA_TO_GAUSS * R0 / R_mean_m
        B_computed_G = d["Bmod"][k, :, 0].mean()
        rel_err = abs(B_computed_G - B_analytic_G) / B_analytic_G
        assert rel_err < 0.07, (
            f"rho={d['rho'][k]:.3f}: Bmod={B_computed_G:.2f} G, "
            f"analytic={B_analytic_G:.2f} G, rel_err={rel_err:.4f}"
        )


def test_q_monotone(chartmap_path):
    """Safety factor q = B_phi / B_theta is broadly increasing with rho."""
    d = _read_chartmap(chartmap_path)
    q = d["B_phi"] / d["B_theta"]
    # Require q to be positive everywhere.
    assert np.all(q > 0), f"q has non-positive values: min={q.min():.4f}"
    # Require q to increase from innermost to outermost (coarse monotonicity).
    assert q[-1] > q[0], (
        f"q not increasing overall: q_inner={q[0]:.4f}, q_outer={q[-1]:.4f}"
    )


def test_q_axis_value(chartmap_path):
    """Innermost q from efit_to_boozer is in a physically plausible range.

    efit_to_boozer field-line integration gives a q profile offset from the
    analytic Q0+... by a factor related to the numerical toroidal flux.
    The innermost q must be in the range [0.8, 2.5] to confirm the converter
    is reading q correctly (not, e.g., returning q=0 or q>>10).
    """
    d = _read_chartmap(chartmap_path)
    q = d["B_phi"] / d["B_theta"]
    q_inner = q[0]
    assert 0.8 < q_inner < 2.5, (
        f"innermost q = {q_inner:.3f}, expected in [0.8, 2.5]"
    )


def test_torflux_sign_and_magnitude(chartmap_path):
    """Toroidal flux is negative (SIMPLE left-handed convention) with correct order of magnitude."""
    d = _read_chartmap(chartmap_path)
    torflux = d["torflux"]
    # SIMPLE/boozer_chartmap convention: torflux < 0.
    assert torflux < 0, f"torflux={torflux:.3e} should be negative"
    torflux_abs = abs(torflux)
    # B0*pi*a^2 = 2*pi*0.25 = 1.57 T*m^2 = 1.57e8 G*cm^2 (geometric approx).
    # The field-line integrator gives psitor_max ≈ 2.5e7 G*cm^2 for this 65x65 grid.
    # Accept within a factor of 10 of the geometric approximation.
    torflux_geom_cgs = B0 * np.pi * A ** 2 * 1.0e8
    assert 0.05 * torflux_geom_cgs < torflux_abs < 5.0 * torflux_geom_cgs, (
        f"torflux={torflux_abs:.3e}, geometric~{torflux_geom_cgs:.3e} G*cm^2"
    )


def test_A_phi_monotone(chartmap_path):
    """A_phi(s) is positive and monotonically increasing with s."""
    d = _read_chartmap(chartmap_path)
    A_phi = d["A_phi"]
    # A_phi = -torflux * integral iota ds with torflux < 0 -> A_phi > 0 and increasing.
    assert A_phi[0] > 0, f"A_phi[0]={A_phi[0]:.3e} should be positive"
    assert A_phi[-1] > A_phi[0], (
        f"A_phi not increasing: A_phi[0]={A_phi[0]:.3e}, A_phi[-1]={A_phi[-1]:.3e}"
    )
